version: '3.7'

services:
  api:
    build:
      context: server/
      target: release
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION: mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:27017/${DB_NAME}
      DB_NAME: ${DB_NAME}
    image: abdennour/go-to-do-api
  db:
    image: bitnami/mongodb:4.4.1
    volumes:
      - db-data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MONGODB_DATABASE: ${DB_NAME}
      MONGODB_USERNAME: ${DB_USER}
      MONGODB_PASSWORD: ${DB_PASS}

volumes:
  db-data: